name: auto-fill-readme

on:
  push:
    branches:
    - main
  workflow_dispatch:


jobs:
  setup-env:
    name: Setup environment variables
    runs-on: ubuntu-latest
    outputs:
      repo_name: ${{ steps.extract.outputs.repo_name }}
      org_name: ${{ steps.extract.outputs.org_name }}

    steps:
    - name: Extract repository details
      id: extract
      run: |
        echo "repo_name=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT
        echo "org_name=${GITHUB_REPOSITORY%/*}" >> $GITHUB_OUTPUT

  replace-placeholders:
    name: Replace placeholders and commit changes
    runs-on: ubuntu-latest
    needs: setup-env # sequential execution
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up environment variables
      env:
        REPO_NAME: ${{ needs.setup-env.outputs.repo_name }}
        ORG_NAME: ${{ needs.setup-env.outputs.org_name }}
      run: |
        echo "Using repo: ${REPO_NAME}"
        echo "Using org: ${ORG_NAME}"
        echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
        echo "ORG_NAME=${ORG_NAME}" >> $GITHUB_ENV

    - name: Replace placeholders in all README.md files
      run: |
        echo "Replacing placeholders in all README.md files..."
        find . -type f -iname "README.md" -print0 | while IFS= read -r -d '' file; do
          echo "Processing $file"
          sed -i "s|{REPO_NAME}|${REPO_NAME}|g" "$file"
          sed -i "s|{ORG_NAME}|${ORG_NAME}|g" "$file"
        done

    - name: Show diff for verification
      run: |
        echo "Checking for changes..."
        git status
        git diff -- README.md || true

    - name: Commit and push changes
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "Changes detected. Committing..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: auto-fill README placeholders"
          git push
        else
          echo "No changes detected, skipping commit."
        fi
