name: go

on:
  pull_request:
    branches:
    - main
    paths:
    - '**.tf'
    - 'examples/**'
    - 'test/**'
    - '.github/workflows/go.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.21.5'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Install dependencies
      run: |
        cd test
        go mod tidy

    - name: Run tests
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: |
        cd test
        go test -v -timeout 30m
